export { default as Layout } from "./src/components/layout"
export { default as SEO } from "./src/components/seo"
export { default as SocialFooter } from "./src/components/socialFooter"
export { default as SocialHeader } from "./src/components/socialHeader"
export { default as baseTheme } from "./src/gatsby-plugin-theme-ui"
