[build]
  base = "www/"
  command = "npm run build"
  publish = "public"
  environment = { NODE_VERSION = "14" }
[context."(ecommerce)--initial-work-on-theme-and-starter"]
  base = "starters/gatsby-starter-catalyst-stripe"
  command = "npm run build"
  publish = "public"
  functions = "functions/"