[build]
  base = "www/"
  command = "npm run build"
  publish = "public"
[context."(stripe)--continued-work-on-theme-and-starter"]
  base = "starters/gatsby-starter-catalyst-stripe"
  command = "npm run build"
  publish = "public"
  functions = "functions/"