[build]
  base = "www/"
  command = "npm run build"
  publish = "public"
[context.\(ecommerce\)--initial-work-on-theme-and-starter]
  base = "starters/gatsby-starter-catalyst-ecommerce"
  command = "npm run build"
  publish = "public"
  functions = "functions/"