name: Publish Sanity Templates

on:
  push:
    branches:
      - main
    paths:
      - "sanity-templates/**"
      - ".github/**"
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: publish:starters
        uses: ehowey/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: sanity-templates ehowey
