name: Test bery Theme
on:
  push:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-bery/**"
      - "themes/gatsby-theme-catalyst-bery/**"
      - "cypress/e2e/bery.test.js"
  pull_request:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-bery/**"
      - "themes/gatsby-theme-catalyst-bery/**"
      - "cypress/e2e/bery.test.js"
jobs:
  test_bery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:bery
          start: yarn serve:bery
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/bery.test.js
