name: Test lithium Theme
on:
  push:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-lithium/**"
      - "themes/gatsby-theme-catalyst-lithium/**"
      - "cypress/e2e/lithium.test.js"
  pull_request:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-lithium/**"
      - "themes/gatsby-theme-catalyst-lithium/**"
      - "cypress/e2e/lithium.test.js"
jobs:
  test_lithium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:lithium
          start: yarn serve:lithium
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/lithium.test.js
