name: Test Helium Theme
on:
  push:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-helium/**"
      - "themes/gatsby-theme-catalyst-helium/**"
      - "cypress/e2e/helium.test.js"
  pull_request:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-helium/**"
      - "themes/gatsby-theme-catalyst-helium/**"
      - "cypress/e2e/helium.test.js"
jobs:
  test_helium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:helium
          start: yarn serve:helium
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/helium.test.js
