name: Test Docs Site
on:
  push:
    branches:
      - main
    paths:
      - "www/**"
      - ".github/**"
      - "cypress/**"
  pull_request:
    branches:
      - main
    paths:
      - "www/**"
      - ".github/**"
      - "cypress/**"
jobs:
  test_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests on Docs
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:www
          start: yarn serve:www
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/docs.test.js
