name: Test Sanity Theme
on:
  push:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-sanity/**"
      - "themes/gatsby-theme-catalyst-sanity/**"
      - "cypress/e2e/sanity.test.js"
  pull_request:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-sanity/**"
      - "themes/gatsby-theme-catalyst-sanity/**"
      - "cypress/e2e/sanity.test.js"
jobs:
  test_sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:sanity
          start: yarn serve:sanity
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/sanity.test.js
