name: Test Basic Theme
on:
  push:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-basic/**"
      - "themes/gatsby-theme-catalyst-basic/**"
      - "cypress/e2e/basic.test.js"
  pull_request:
    branches:
      - main
    paths:
      - "starters/gatsby-starter-catalyst-basic/**"
      - "themes/gatsby-theme-catalyst-basic/**"
      - "cypress/e2e/basic.test.js"
jobs:
  test_basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:basic
          start: yarn serve:basic
          config-file: cypress/cypress-github-actions.json
          spec: cypress/e2e/basic.test.js
